{% set name = "rsa" %}
{% set version = "4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 109ea5a66744dd859bf16fe904b8d8b627adafb9408753161e766a92e7d681fa

build:
  number: 0
  entry_points:
    - pyrsa-priv2pub = rsa.util:private_to_public
    - pyrsa-keygen = rsa.cli:keygen
    - pyrsa-encrypt = rsa.cli:encrypt
    - pyrsa-decrypt = rsa.cli:decrypt
    - pyrsa-sign = rsa.cli:sign
    - pyrsa-verify = rsa.cli:verify
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - pyasn1 >=0.1.3
    - python

test:
  imports:
    - rsa
  commands:
    - pip check
    - pyrsa-priv2pub --help
    - pyrsa-keygen --help
    - pyrsa-encrypt --help
    - pyrsa-decrypt --help
    - pyrsa-sign --help
    - pyrsa-verify --help
  requires:
    - pip

about:
  home: https://stuvel.eu/rsa
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pure-Python RSA implementation

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
