travis:
  secure:
    BINSTAR_TOKEN: iNuaKJcGFCyIKiqWQxtZ9fRvfmm2o7Q6Lee0UyTdrLuko6IAqIi1/NXdhd7l9PcaTDAhEpbtuq7wz6GSGcw23uyDixYxKwl0p1/G2+o4b9hGKuWdGqLS69OMnJyy0s4n2SVxOPuOhOZMgSoAvoZUqmoW9zl+U5f5Xw1OjjMw3sd8EzHfu4xTvDKUjMa5cRp6m1ZIS3lDmeCx4J+VjYBOFYDSih3tgS2dBBDxDw7GVqFywiSGQtrooUkA+OzAQzJVZeLqEYqzpiemq48SVVZvmEZEIWSB0gba6e4ToDhUyBpPEykOlFyFf/UBFkkRlw8Ydi/9lxUnxBPE6Q9Thvl6ag8VZCkzR6P86hok8i9DcdSSildXCK2Fe0+b+3PPRiajha9ad4bql84f42cparcEUhgW6JdL1o4D73iPJnS1IAnvQ2vTe4lr8CmPxLTnP10JDIVpPZgZ0L1neQP0RbuEOpcPn4JuHf+MEsAf8ih2aSZEK8m6mP3ugQQd2qxUsx2xuaqvs+sDlxHy6Geu4Pdypf75QJA7MpSZzC45tlk7XVHIf5o8W6VORmiDJjBTM+Nkc52hMa7+F/USHPclQFTZjJQDkEy8Z6U/33VnhoisRcrg7uNRfg+ZgUppfmG9zPykTCR5/bnXkE8vyz9sE43bil8XQeQYFnnlNHjHCDV/nAg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
