travis:
  secure:
    BINSTAR_TOKEN: PNSdFNvrAVUSWYNOH3Mnk0rhNMTk/B6jU7dK/ie7vUfcC/q6V5S9mb2iGtwZTqdhwaW7x3JxKEiw5Pc9m1EwlDnfHdin6dCaPvmAU72AjN5FzjSGOyTMD4pisfKdLTg9g/khYNjugtTY5kUbZ2KfNVlDxAfUsJpboKGclhuWYGDnIJ9ya80isgdCIrrfDG5g/SM4o/gmC3Xh61i6/XfrzNsKqc35tFtOti+WOfBQHBspks353aeTADBvIKvx9ga4d8JJHYa41f8eCMEJJavk9GZoLUBo2b/TZTY9yS7kb/HUTxCOwCsRyLkMOJQj8wSQxfUGJDcMQrJA23AlZL5Sdvb/SmF+tIc5BWFgak4/CyNGSe9UEbj8g58JoJ27tqz8wLpxy+7zSlLbrFP/GQkY6aAxEZwydLwzMj6UCSq/wZTR8G9RsA6Wh0ZHAxDa1rTvMG92VUHRmiJnbjX4yULodHIYTkbpxf1M1t50ZnwnlLnmVvqTfG80iQvH4T6M7p26TPx3MXWqYxAJ1eB9dXdsNWoVbNKVnmQF2zhjskGuqI5Rgp5uz0AWiWxUiAmyOfkRZUBCkcmKQaoTWQlw2hW5ZklpxubFJN9aYVWK7qvqbDkkn86xH+zsED0lnRJ2uFemtQ9uo2ET1uBKLZDpdA/BffJuPd9ISVepH3VkjR+5SAc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
