travis:
  secure:
    BINSTAR_TOKEN: RC1i9WK520CtS7xeM0XrtaDgZHVPng+z4U5KxnPlBwJrhRPNKXXVehkCpoLRPogggs/V1seCkyh3PoMBWLOh4upRVcwkk6RT6zuaE+jA3iaI7Urks3ctM1rpCguRVYht2wrkXeiylzKaTntxVP+NT9gbqhGAlJacRVkWvIUZHbNwqzPai9Y29TD6iF63gzU1Ucfrc/GKgrNVtP5REmVpGKxisJp+SXDOElkvtOXBchafxj+Op0/9eo7+ejol8m2OUb+f0stTDiIZksInGqZjBosT10N/CtBP8PmOqAg4MkXOrS33uizBSn7wtvhATyvfCbizB4QD09xewgZMGwDRK7KlIxTZuLh0N4S/8S9ymgrn2GKodFEVMrZXUuqdTqIy0LRa+Mevbaa5RnwM1vXh/7DDqxqDoD4QYQjvdiLYUyvPxcJNV6PfjewfZdUNCxWlpfd09oavDWp/bqptXAahYTx8rzA1JV/NwwuuIyvZgY0A0hbmnnMgKB8LDa5spm9FQP1977RLgURy78AhOsW2CUc8ILH0H3jaj8F/nLdzRc/Qux9T7Hb8fFrkNXHRjmCaNYVNry1s/+zqMLRWZDsbDWZEQK+Qnl8mTt/6HUtUFpsQnD0ma3hElUg2TgfjQabTZRE7EZFLqGGTP9gAdF17IG2WqahIl4cEmzQgYkaW3qs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
